#!/bin/bash

### BEGIN INIT INFO
# Provides:          machineid
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Changing machineid to random value
# Description:       Changing machineid to random value
### END INIT INFO

old=$(cat /etc/machine-id)
new=$(tr -dc 'A-Z0-9' < /dev/urandom | head -c32)
sed -i "s/$old/$new/g" /var/lib/dbus/machine-id
sed -i "s/$old/$new/g" /etc/machine-id

exit 0
